# Generated by Django 2.2.1 on 2019-05-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='blog.Article'),
        ),
    ]
